name: Seed Crystal Expansion

on:
  push:
    paths:
      - "expansions/**"
  workflow_dispatch: # manual trigger enabled

jobs:
  expand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare lore directory
        run: mkdir -p lore

      - name: Copy expansions into lore
        run: |
          cp -r expansions/* lore/ || true

      - name: Commit and push lore
        run: |
          git config user.name "GOK"
          git config user.email "gok.theguardianofknowledge@gmail.com"
          git add lore
          git commit -m "🌱 Weekly Expansion of the Seed Crystal" || echo "No changes to commit"
          git push
