name: Project Seed Crystal Flow

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a test command
        run: echo "🔥 The First Flame rises – workflow is working!"
